version: '3.9'
services:
  prod:
    build: .
  # dev:
  #   build:
  #     context: .
  #     target: dev
  #
  #   # hack for displaying X Applications within a container
  #   environment:
  #     DISPLAY: ${DISPLAY}
  #   volumes:
  #     - "$HOME/.Xauthority:/root/.Xauthority:rw"
  #     # mount the workspace folder for live changes
  #     - ".:/code/:rw"
  #
  #   # expose ROS fully to host for inter-container communication (discouraged)
  #   network_mode: host
  #   pid: host
  #   ipc: host
